/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.alx.kpij.UnitConverter;

import java.awt.Color;

/**
 *
 * @author Adi
 */
public class UnitConverter extends javax.swing.JFrame {

    /**
     * Creates new form UnitConverter
     */
    public UnitConverter() {
        initComponents();
        this.setLocation(300, 200);
        this.getContentPane().setBackground(new Color(20, 200, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        unitList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        unitList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        correctLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valueField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konwerter jednostek");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Jednostka X");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Jednostka Y");

        convertButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        convertButton.setText("Przelicz");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        unitList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cale", "Celcjusze", "Centymetry", "Farenheity", "Funty", "Gramy", "Jardy", "Kelwiny", "Kilogramy", "Kilometry", "Metry", "Mile", "Stopy", "Uncje", "UK Galon", "US Galon", "Litry" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(unitList1);

        unitList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cale", "Celcjusze", "Centymetry", "Farenheity", "Funty", "Gramy", "Jardy", "Kelwiny", "Kilogramy", "Kilometry", "Metry", "Mile", "Stopy", "Uncje", "UK Galon", "US Galon", "Litry" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(unitList2);

        resultArea.setColumns(20);
        resultArea.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        resultArea.setRows(5);
        jScrollPane3.setViewportView(resultArea);

        correctLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        correctLabel.setForeground(new java.awt.Color(102, 0, 0));
        correctLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctLabel.setText("Wybierz jednostkę X do przeliczenia na jednostkę Y");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Podaj wartość:");

        valueField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addComponent(correctLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(convertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                .addComponent(correctLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
       
        double value = 0.0;
        double result = 0.0;
        try {
            value = Double.parseDouble(valueField.getText());
            if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 2 ){
                result = value * 2.54;
                showResult(result);
            } else if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 6 ){
                result = value * 0.027778;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 9 ){
                result = value / 39370;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 10 ){
                result = value / 39.370;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.00001578;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 0 && unitList2.getSelectedIndex() == 12 ){
                result = value * 0.083333;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 1 && unitList2.getSelectedIndex() == 3 ){
                result = value * 1.8 + 32.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 1 && unitList2.getSelectedIndex() == 7 ){
                result = value + 273.15;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 0 ){
                result = value * 0.39370;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 6 ){
                result = value * 0.010936;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 9 ){
                result = value / 100000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 10 ){
                result = value / 100.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.000006213;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 2 && unitList2.getSelectedIndex() == 12 ){
                result = value * 0.032808;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 3 && unitList2.getSelectedIndex() == 1 ){
                result = (value - 32.0)/1.8;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 3 && unitList2.getSelectedIndex() == 7 ){
                result = (value - 32.0)/1.8 + 273.15;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 4 && unitList2.getSelectedIndex() == 5 ){
                result = value / 0.0022046;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 4 && unitList2.getSelectedIndex() == 8 ){
                result = value / 2.2046;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 4 && unitList2.getSelectedIndex() == 13 ){
                result = value * 16;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 5 && unitList2.getSelectedIndex() == 4 ){
                result = value * 0.0022046;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 5 && unitList2.getSelectedIndex() == 8 ){
                result = value / 1000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 5 && unitList2.getSelectedIndex() == 13 ){
                result = value * 0.035274;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 0 ){
                result = value * 36.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 2 ){
                result = value / 0.010936;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 9 ){
                result = value / 1093.6;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 10 ){
                result = value / 1.0936;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.00056818;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 6 && unitList2.getSelectedIndex() == 12 ){
                result = value * 3;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 7 && unitList2.getSelectedIndex() == 1 ){
                result = value - 273.15;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 7 && unitList2.getSelectedIndex() == 3 ){
                result = (value - 273.15) * 1.8 + 32.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 8 && unitList2.getSelectedIndex() == 4 ){
                result = value * 2.2046;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 8 && unitList2.getSelectedIndex() == 5 ){
                result = value * 1000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 8 && unitList2.getSelectedIndex() == 13 ){
                result = value * 35.274;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 0 ){
                result = value * 39370.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 2 ){
                result = value * 100000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 6 ){
                result = value * 1093.6;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 10 ){
                result = value * 1000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.62137;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 9 && unitList2.getSelectedIndex() == 12 ){
                result = value * 3280.8;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 0 ){
                result = value * 39.370;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 2 ){
                result = value * 100.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 6 ){
                result = value * 1.0936;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 9 ){
                result = value / 1000.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.00062137;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 10 && unitList2.getSelectedIndex() == 12 ){
                result = value * 3.2808;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 0 ){
                result = value * 63360.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 2 ){
                result = value * 0.000006213;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 6 ){
                result = value * 1760.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 9 ){
                result = value / 0.62137;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 10 ){
                result = value * 0.00062137;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 11 && unitList2.getSelectedIndex() == 12 ){
                result = value * 5280.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 0 ){
                result = value * 12.0;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 2 ){
                result = value * 0.032808;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 6 ){
                result = value * 0.33333;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 9 ){
                result = value / 3280.8;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 10 ){
                result = value / 3.2808;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 12 && unitList2.getSelectedIndex() == 11 ){
                result = value * 0.00018939;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 13 && unitList2.getSelectedIndex() == 4 ){
                result = value * 0.0625;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 13 && unitList2.getSelectedIndex() == 5 ){
                result = value / 0.035274;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 13 && unitList2.getSelectedIndex() == 8 ){
                result = value / 35.274;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 14 && unitList2.getSelectedIndex() == 15 ){
                result = value * 1.2009;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 14 && unitList2.getSelectedIndex() == 16 ){
                result = value / 0.21997;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 15 && unitList2.getSelectedIndex() == 14 ){
                result = value * 0.83267;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 15 && unitList2.getSelectedIndex() == 16 ){
                result = value / 0.26417;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 16 && unitList2.getSelectedIndex() == 14 ){
                result = value * 0.21997;
                showResult(result);
            }else if (unitList1.getSelectedIndex() == 16 && unitList2.getSelectedIndex() == 15 ){
                result = value * 0.26417;
                showResult(result);
            } else {
                correctLabel.setForeground(Color.RED);
                correctLabel.setText("Nie poprawnie wybrane jednostki!!!");
            }
            
            
            
            
        } catch (NumberFormatException e){
            correctLabel.setForeground(Color.RED);
            correctLabel.setText("Podano złą wartość liczbową!!!");
        }
    }//GEN-LAST:event_convertButtonActionPerformed
    public void showResult(double value){
        correctLabel.setForeground(Color.BLUE);
        correctLabel.setText("Oto wynik:");
        String valueString = String.format("%.4f", value);
        resultArea.setText(valueString);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JList<String> unitList1;
    private javax.swing.JList<String> unitList2;
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
}
